### ISSUE TITLE
Users should be able to delete accounts

### ISSUE THREAD

**Issue by RogerTangos** [datahuborg/datahub#104]
Corresponds with DAT-49

Just a bit of an update on this: I've been developing user and database removal on the openid-connect-manager branch. I also wrote some tests for this a while back, on a feature/delete_users branch... But user management has changed so much that I'm not sure how much of this is left to be salvaged.

My primary motivation for developing on the openid-connect-manager branch is that the functional tests occasionally exit without using `teardown`... This made them pretty much useless.

Presently, users are able to be deleted programmatically through function calls accessible in manager.py. Previous to the commits, it was not possible to delete users that had added collaborators to their repos.

Still to do:
 - Ensuring that user's files are deleted
 - Adding a hook to `user.delete`, so that this only requires one call to do.
 - UX

**Comment by justinanderson** [comment]
Heads up that I'll be creating a user settings for other account related things, so if you make a user delete action I can link it from there.

**Comment by RogerTangos** [comment]
Closed in #107.
