### ISSUE TITLE
DATAQ --> Add Table and Select Columns: Ability to select ALL

### ISSUE THREAD

**Issue by b44p** [datahuborg/datahub#110]
How do I select all columns using Data Q or are users expected to edit the SQL text (select * ... )

Tx

**Comment by justinanderson** [comment]
To select all columns with DataQ, click Add Table, choose the table you want from the dropdown menu, and then turn on each column.

There's no shortcut for selecting all columns, though that would be a good feature request.

**Comment by RogerTangos** [comment]
DataQ was updated in PR #149. I believe you can now hold shift to select
