### ISSUE TITLE
Users without an upload folder can't log in

### ISSUE THREAD

**Issue by justinanderson** [datahuborg/datahub#111]
New users get a user_data folder during account creation, but users from before the OIDC migration who never uploaded a file don't have a user_data folder. Those users with a Django user, db role, and db, but no user_data folder fail the [pre-save validation](https://github.com/datahuborg/datahub/blob/master/src/account/signals.py#L37).

We should either create user_data folders for all legacy users who still exist as current users, or we should relax that validator to not care about user_data folders. Probably the first.

**Comment by RogerTangos** [comment]
Sounds like a simple script could do it. Are we currently supporting old deployments of datahub, or assuming that everyone starts fresh (since v0.3, anyhow)?

**Comment by justinanderson** [comment]
Yeah, I was thinking another django management script.

It isn't a concern unless a site has upgraded to 0.3. Are there any deployments of datahub with users besides datahub.csail.mit.edu?

**Comment by RogerTangos** [comment]
BT, and @karger mentioned that one student had it up and running? I was thinking that we might want to start including migration scripts in another repo.

**Comment by justinanderson** [comment]
Why another repo? The scripts so far are tied to needs introduced by new versions of the site. Sites that haven't upgraded yet wouldn't have need of them.

**Comment by RogerTangos** [comment]
Here works too. I was thinking that since migration scripts aren't tightly tied to new deployments.

**Comment by RogerTangos** [comment]
created a script in #112

**Comment by RogerTangos** [comment]
@justinanderson - pinging you on this. Are we waiting for feature/rest to merge, or for something else?

**Comment by justinanderson** [comment]
Totally forgot about it.

**Comment by RogerTangos** [comment]
Np. That's just what cleaning issues is about :)
