### ISSUE TITLE
Can't register a numerical username

### ISSUE THREAD

**Issue by willjharmer** [datahuborg/datahub#120]
When registering with a User ID, something common to the corporate world (I'm just a number!), I get a Postgres role create error. E.g. I register with the following example details:
Username: 123456789
Email: example.user@mycorp.com
Password: password

Error log attached:
[Account registration error.pdf](https://github.com/datahuborg/datahub/files/161229/Account.registration.error.pdf)

**Comment by RogerTangos** [comment]
Hey @willjharmer - Thanks for logging this. It's a known issue and a side effect of making postgres roles that match datahub usernames. That needs to be worked out (It's also related to #58, #59, and to some extent, #61.) but it requires some major surgery that we haven't been able to do yet.

**Comment by RogerTangos** [comment]
Duplicated under #146
