### ISSUE TITLE
Glitch with datatables

### ISSUE THREAD

**Issue by kxzhang** [datahuborg/datahub#124]
Whenever I visit one of the tables I have created, it loads all the rows (briefly for half a second) before refreshing and applying row level security / filtering out the rows that I don't have access to. 

This is on branch rowlevelsecurity.

**Comment by RogerTangos** [comment]
Issue has to do with the datatables app, which takes over when viewing a table. We'll probably want to be removing datatables, anyhow.

**Comment by RogerTangos** [comment]
dfa732d8d237f6c9544ce4156a474d00fd957cf0

**Comment by RogerTangos** [comment]
DataTables should just be removed and replaced. #163
