### ISSUE TITLE
Console cleanup

### ISSUE THREAD

**Issue by justinanderson** [datahuborg/datahub#138]
The console work on feature/rest needs a few things before it's ready for deployment:

- [x] Console should be using https for all of its calls, including its AJAX calls. It's using http now because that was the easiest way to get functional tests working with PhantomJS, but that's not something we can do for live usage. console.html is a Django template, so the scheme can be passed in at runtime as a context variable, with its value dependent on whether it's in a test or real usage.

- [x] Instead of repeating console's client ID in console.html and the data migration that registers the console app as an OAuth client, the client ID should be defined in settings.py (or maybe local_settings.py) and used that way, to reduce the number of times it's hardcoded in the project.

- [x] Should remove comments like "// this may not work".

- [x] The docs don't need to mention that it uses the API now. I would say that's not important to someone reading the docs.

- [x] To be complete, the docs should include the console's help command.

- [x] I haven't tested this, but I think the regex for connect is too fuzzy. `/\\?connect$|^\\c$/` matches "connect", "\connect", and "\c", but also "disconnect" and "dis\connect".

- [x] The data migration that creates an OAuth client registration for console shouldn't [create an owner named foo](https://github.com/datahuborg/datahub/commit/3f92d81d8fa0a2d22eda8b1e10f9395221d6050c#diff-5e0c4dac1e5f85031a7bdaa8d6755400R31). That migration mutes signals and skips validation, so it might as well have a username that no user could log in as or try to reset the password of.

**Comment by RogerTangos** [comment]
Console is now using https when not in testing. Should the client_id be secret, or is it OK to throw it into `settings.py`?

**Comment by justinanderson** [comment]
Different deployments of DataHub may want to have their own client_id for Console, but it doesn't have to be secret. As long as it has a default client_id in settings.py which is overridable via local_settings.py.

**Comment by RogerTangos** [comment]
re:  shouldn't create an owner named foo, I'm thinking of making a special owner for all of the main oauth2 applications. Sound OK to you?

**Comment by justinanderson** [comment]
👍

**Comment by RogerTangos** [comment]
closed in 2d2a5725e45628cae6703add029e1c0e5ed72c68
