### ISSUE TITLE
disconnect stack in console

### ISSUE THREAD

**Issue by RogerTangos** [datahuborg/datahub#43]
It should be possible disconnect from the current repo in the terminal. In postgres, this should be with the ``disconnect command`` and/or ``ctrl+d``, but I'm not sure how other databases manage it.

**Comment by RogerTangos** [comment]
Hey @ginayuan - can you please make sure that this feature makes it into the console rewrite?

**Comment by ygina** [comment]
CTRL+d to exit out of connections to other users since 45c8ed2426313d650b6e73371b26a1224e4ce162
