### ISSUE TITLE
Console cannot list views

### ISSUE THREAD

**Issue by RogerTangos** [datahuborg/datahub#46]
Go to the console, then `ls reponame`

Base tables will show, but views won't.

This happens because the list_tables method now only lists base tables. Unfortunately, I'm having trouble getting Thrift (0.9.2) to generate up-to-date javascript code which will allow a javascript `client.ls_views` function.

**Comment by ygina** [comment]
Can list views in console as of 45c8ed2426313d650b6e73371b26a1224e4ce162 with ``ls <repo-name>``
