### ISSUE TITLE
Apps should be listed in app center

### ISSUE THREAD

**Issue by RogerTangos** [datahuborg/datahub#50]
The "Apps Center" link on the top nav bar currently points to root. There should either be a list of installed apps, or the link should be removed.

**Comment by RogerTangos** [comment]
@abhardwaj  tells me that the original purpose of the app center link was to provide a list of links to *external* applications, that could communicate with datahub via its API. This seems like a looser version of the openPDS Q&A model.

Right now, we have some linguistic confusion between our different types of apps:

1. Apps communicating with DH using the thrift API. (GetFit + Confer)
2. Other apps using a yet-to-be-spec'd REST API
3. Django apps installed on the DataHub system, making direct use of the datahub python core (DataQ, Console, DataTables, etc).

It seems like category 1 is deprecated; but that categories 2 and 3 really need some updated names, if only to avoid confusion with potential open source developers. 

I'm moving this discussion to flowdoc to help resolve it. If you would like to chime in, but aren't on flowdoc, please chime in here.

**Comment by karger** [comment]
what/where is flowdoc?

**Comment by RogerTangos** [comment]
We're using slack (I misspoke initially). It's an IRC alternative that can
be integrated into Jira (an agile story tracker) and Github. I sent you an
invite in a PM.

Albert Carter

Programmer
Big Data Initiative
CSAIL, MIT

**Comment by qqliu** [comment]
I currently have an app that relies on Datahub API, please also include me
in this communication.

Thank you!

Cheers,

Quanquan

**Comment by RogerTangos** [comment]
Hey Qanqan,

What app are you maintaining? We're working on building a REST API for client applications, and (once this is done) giving people some time to migrate from Thrift.

**Comment by karger** [comment]
(1) http://kibitz.csail.mit.edu/
(2) I doubt Quanquan is using the thrift libraries directly; rather, she 
is using the (python?) library you wrote to allow data passing to/from 
datahub into python apps, so presumably won't notice if you replace 
thrift with your own rest api.

**Comment by karger** [comment]
please invite karger@mit.edu instead.

**Comment by RogerTangos** [comment]
You should have received an invitation a few minutes ago.

Albert Carter

Programmer
Big Data Initiative
CSAIL, MIT

**Comment by qqliu** [comment]
I'm using the Java API library. If the function calls within the Java
library do not change, then, there should be no effect on my application,
Kibitz.

**Comment by abhardwaj** [comment]
Don't worry -- we aren't going to get rid of thrift APIs -- we will support
the deprecated APIs at least until your CHI submission.

You would only need to change the URL http://datahub.csail.mit.edu/service
to http://datahub.csail.mit.edu/api/unsupported/thrift

**Comment by RogerTangos** [comment]
PR #154 includes buttons for the apps, and fixes previously broken app functionality.
