### ISSUE TITLE
Tables created in public aren't visible to anyone

### ISSUE THREAD

**Issue by RogerTangos** [datahuborg/datahub#73]
When users don't specify a schema for table creation, the table ends up in PUBLIC. The system should warn them of this, and possibly disallow tables in the public schema.

**Comment by RogerTangos** [comment]
Reported by @b-carter :
I ran this query inside a repository called “userdata”:
CREATE TABLE Persons ( PersonID int, LastName varchar(255), FirstName varchar(255), Address varchar(255), City varchar(255) );

The query succeeded, and if I try to re-run it, I get an error that the table already exists.

I didn’t see the table in my repository (or anywhere), so I then ran another query:
CREATE TABLE userdata.Persons ( PersonID int, LastName varchar(255), FirstName varchar(255), Address varchar(255), City varchar(255) );

Response by @justinanderson : Every user's repo in DataHub is a schema in Postgres, and every database gets a 'public' schema by default. The "Run SQL" text field on DataHub lets you enter any SQL you want, including CREATE TABLE commands, so if you create a table without specifying which schema it should go into, it goes into the public schema. DataHub's UI doesn't show anything in the public schema, so that table is invisible but still addressable via Run SQL commands.

**Comment by anantb** [comment]
This is due to a template file which sets the default schema to 'public' --
if you delete the template file -- it will complain asking the user to put
the schema name.

**Comment by RogerTangos** [comment]
Thanks! Do you remember which file?

**Comment by anantb** [comment]
All the databases created on postgres are based on a template database
called template1 (see below). This template database automatically creates
a schema called public and sets it in the search_path for tables (if you
don't use <schema>.<table> notation. You should delete the default schema
from template1 (or create another template and use that template for all
create_db). Also, remove 'public' and "$user" from the search path.


ubuntu@datahub-prod-01:~$ psql -U postgres -W -h localhost

Password for user postgres:

psql (9.3.10)

SSL connection (cipher: DHE-RSA-AES256-GCM-SHA384, bits: 256)

Type "help" for help.


postgres=# \c template1

Password for user postgres:

SSL connection (cipher: DHE-RSA-AES256-GCM-SHA384, bits: 256)

You are now connected to database "template1" as user "postgres".

template1=# \dn

  List of schemas

  Name  |  Owner

--------+----------

 public | postgres

(1 row)


template1=# SHOW search_path;

  search_path

----------------

 "$user",public

(1 row)

**Comment by RogerTangos** [comment]
Spoke with @karger and @justinanderson about this. The current plan is to disable public tables. When people fail to prepend their table names with a schemaname (i.e. `tablename` instead of `schema.tablename`), we'll default to whatever schema they're in.

**Comment by anantb** [comment]
+1

**Comment by RogerTangos** [comment]
76ae5a1 feature/rest goes part way to this, by defaulting to a user's current repo. We haven't totally disabled public schemas yet though. Expect this to be integrated into datahub at the end of February/start of March.

**Comment by RogerTangos** [comment]
closed in c30c286dc83957c2685dc3f1af7b31b6b8bc7db2

The public repo is no longer a part of template1. Existing schemas named 'public' are migrated to another non-colliding name
